import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "all-about-next14",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header style={{ backgroundColor: "lightblue", padding: "1rem" }}>
          header
        </header>
        {children}
        <footer
          style={{ backgroundColor: "lightgoldenrodyellow", padding: "1rem" }}
        >
          footer
        </footer>
      </body>
    </html>
  );
}
